X_n = (X ./ (const.c));
        Y_n = (Y ./ const.c*sqrt(3));
        Q = ((cos(2*pi*((X ./ (const.c))-(Y ./ const.c*sqrt(3))))+cos(4*pi*(Y ./ const.c*sqrt(3)))+cos(2*pi*((X ./ (const.c))+(Y ./ const.c*sqrt(3))))) + 3/2)/(4.5);
    V = (V0func(Z,const.zOffset+2.1,25,1.2) ...
       + V1func(Z,const.zOffset+3.7,0.5,1.6))...
    * ((cos(2*pi*((X ./ (const.c))-(Y ./ const.c*sqrt(3))))+cos(4*pi*(Y ./ const.c*sqrt(3)))+cos(2*pi*((X ./ (const.c))+(Y ./ const.c*sqrt(3))))) + 3/2)/(4.5)
       + (V0func(Z,const.zOffset+2.15,20,1.2) + ...
      + V1func(Z,const.zOffset+3,0,1.1)) ...
      * Qhexfunc(X-const.c/2,Y-(const.c*1/(2*sqrt(3)))) ...
    * ((cos(2*pi*(((X-1/2) ./ (const.c))-((Y-1/2) ./ const.c*sqrt(3))))+cos(4*pi*(Y ./ const.c*sqrt(3)))+cos(2*pi*((X ./ (const.c))+(Y ./ const.c*sqrt(3))))) + 3/2)/(4.5)
      + (V0func(Z,const.zOffset+2.1,23,1.2) ...
      + V1func(Z,const.zOffset+1,15,1.1)) ...
    Q = ((cos(2*pi*((X ./ (const.c))-((Y-1) ./ const.c*sqrt(3))))+cos(4*pi*(Y ./ const.c*sqrt(3)))+cos(2*pi*((X ./ (const.c))+(Y ./ const.c*sqrt(3))))) + 3/2)/(4.5);
      * Qhexfunc(X,Y - (const.c/sqrt(3)));