X_n = X ./ (const.c);
        Y_n = Y ./ (const.c*sqrt(3));
        Q = ((cos(2*pi*(X_n-Y_n))+cos(4*pi*Y_n)+cos(2*pi*(X_n+Y_n))) + 3/2)/(4.5);
        %Q = cos(2*pi*nu/const.a)^5 + cos(2*pi*mu/const.a)^5;
    V = (V0func(Z,const.zOffset+2.1,25,1.2) ...
       + V1func(Z,const.zOffset+3.7,0.5,1.6))... %blue
       * Qhexfunc(X,Y) ...
       + (V0func(Z,const.zOffset+2.15,20,1.2) + ...
      + V1func(Z,const.zOffset+3,0,1.1)) ... % green
      * Qhexfunc(X-const.c/2,Y-(const.c*1/(2*sqrt(3)))) ...
      + (V0func(Z,const.zOffset+2.1,23,1.2) ...
      + V1func(Z,const.zOffset+1,15,1.1)) ... %red
      * Qhexfunc(X,Y - (const.c/sqrt(3)));
      %VmatrixElement = Qhexfunc(X,Y) * Dropoff(Z) * const.D;
