 V0func(z,z0,backgroundDepth,alpha)
        V01 = (backgroundDepth1 * exp(2*alpha1*(z01-z))-2*backgroundDepth1*exp(alpha1*(z01-z)))
        V02 = (backgroundDepth2 * exp(2*alpha2*(z02-z))-2*backgroundDepth2*exp(alpha2*(z02-z)))
        V03 = (backgroundDepth2 * exp(2*alpha3*(z03-z))-2*backgroundDepth3*exp(alpha3*(z03-z)))
    end
V1func(z,z0,D,alpha)
        V1 = (2*const.beta*D*exp(2*alpha*(z0-z)))

X_n = (X ./ (const.c));
        Y_n = (Y ./ const.c*sqrt(3));
        Q = ((cos(2*pi*((X ./ (const.c))-(Y ./ const.c*sqrt(3))))+cos(4*pi*(Y ./ const.c*sqrt(3)))+cos(2*pi*((X ./ (const.c))+(Y ./ const.c*sqrt(3))))) + 3/2)/(4.5);

    V = ((backgroundDepth1 * exp(2*alpha1*(z01-z))-2*backgroundDepth1*exp(alpha1*(z01-z))) ...
       + (2*const.beta*D0*exp(2*beta1*(z11-z))))...
    * ((cos(2*pi*((X ./ (const.c))-(Y ./ const.c*sqrt(3))))+cos(4*pi*(Y ./ const.c*sqrt(3)))+cos(2*pi*((X ./ (const.c))+(Y ./ const.c*sqrt(3))))) + 3/2)/(4.5)
       + ((backgroundDepth2 * exp(2*alpha2*(z02-z))-2*backgroundDepth2*exp(alpha2*(z02-z))))
    * ((cos(2*pi*(((X-1/2) ./ (const.c))-((Y-1/2) ./ const.c*sqrt(3))))+cos(4*pi*(Y ./ const.c*sqrt(3)))+cos(2*pi*((X ./ (const.c))+(Y ./ const.c*sqrt(3))))) + 3/2)/(4.5)
      + ((backgroundDepth3 * exp(2*alpha3*(z03-z))-2*backgroundDepth3*exp(alpha3*(z03-z))) ...
      + (2*const.beta*D3*exp(2*beta3*(z33-z)))) ...
    * ((cos(2*pi*((X ./ (const.c))-((Y-1) ./ const.c*sqrt(3))))+cos(4*pi*(Y ./ const.c*sqrt(3)))+cos(2*pi*((X ./ (const.c))+(Y ./ const.c*sqrt(3))))) + 3/2)/(4.5);


    ((backgroundDepth1 * exp(2*alpha1*(z01-z))-2*backgroundDepth1*exp(alpha1*(z01-z))) ...
       + (2*const.beta*D0*exp(2*beta1*(z11-z)))) ...
    * ((cos(2*pi*((X ./ (const.c))-(Y ./ const.c*sqrt(3))))+cos(4*pi*(Y ./ const.c*sqrt(3)))+cos(2*pi*((X ./ (const.c))+(Y ./ const.c*sqrt(3))))) + 3/2)/(4.5) ...
       + ((backgroundDepth2 * exp(2*alpha2*(z02-z))-2*backgroundDepth2*exp(alpha2*(z02-z))))
    * ((cos(2*pi*(((X-1/2) ./ (const.c))-((Y-1/2) ./ const.c*sqrt(3))))+cos(4*pi*(Y ./ const.c*sqrt(3)))+cos(2*pi*((X ./ (const.c))+(Y ./ const.c*sqrt(3))))) + 3/2)/(4.5) ...
      + ((backgroundDepth3 * exp(2*alpha3*(z03-z))-2*backgroundDepth3*exp(alpha3*(z03-z))) ...
      + (2*const.beta*D3*exp(2*beta3*(z33-z)))) ...
    * ((cos(2*pi*((X ./ (const.c))-((Y-1) ./ const.c*sqrt(3))))+cos(4*pi*(Y ./ const.c*sqrt(3)))+cos(2*pi*((X ./ (const.c))+(Y ./ const.c*sqrt(3))))) + 3/2)/(4.5);